global CONFIG_FILE_PATH := "config.json"

; https://docs.microsoft.com/en-us/windows/win32/intl/wm-ime-control
global WM_IME_CONTROL := 0x0283

; 下面几个IMC消息可能在高版本系统中不受支持，但目前在win11 22598.1版本中仍工作良好
; https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms920838(v=msdn.10)
global IMC_GETOPENSTATUS := 0x0005
global IMC_SETOPENSTATUS := 0x0006

; https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms920931(v=msdn.10)
global IMC_GETCONVERSIONMODE := 0x0001
global IMC_SETCONVERSIONMODE := 0x0002

/**
 * 参考：
 * https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registershellhookwindow
 * https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms644991(v=vs.85)
 * https://github.com/tpn/winsdk-10/blob/master/Include/10.0.10240.0/um/WinUser.h
 */
global HSHELL_WINDOWCREATED := 1	; A top-level, unowned window has been created. The window exists when the system calls this hook.
global HSHELL_WINDOWDESTROYED := 2	; A top-level, unowned window is about to be destroyed. The window still exists when the system calls this hook.
global HSHELL_ACTIVATESHELLWINDOW := 3	; The shell should activate its main window.
global HSHELL_WINDOWACTIVATED := 4	; The activation has changed to a different top-level, unowned window.
global HSHELL_GETMINRECT := 5	; A window is being minimized or maximized. The system needs the coordinates of the minimized rectangle for the window.
global HSHELL_REDRAW := 6	; The title of a window in the task bar has been redrawn.
global HSHELL_TASKMAN := 7	; The user has selected the task list. A shell application that provides a task list should return TRUE to prevent Windows from starting its task list.
global HSHELL_LANGUAGE := 8	; Keyboard language was changed or a new keyboard layout was loaded.
global HSHELL_SYSMENU := 9
global HSHELL_ENDTASK := 10	; A handle to the window that should be forced to exit.
global HSHELL_ACCESSIBILITYSTATE := 11	; The accessibility state has changed.
global HSHELL_APPCOMMAND := 12	; The user completed an input event (for example, pressed an application command button on the mouse or an application command key on the keyboard), and the application did not handle the WM_APPCOMMAND message generated by that input. if the Shell procedure handles the WM_COMMAND message, it should not call CallNextHookEx. See the return Value section for more information.
global HSHELL_WINDOWREPLACED := 13	; A top-level window is being replaced. The window exists when the system calls this hook.
global HSHELL_WINDOWREPLACING := 14	; A handle to the window replacing the top-level window.

global HSHELL_MONITORCHANGED := 16	; A handle to the window that moved to a different monitor.

global HSHELL_FLASH := 32774	; The title of a window in the task bar has been redrawn.
global HSHELL_RUDEAPPACTIVATED := 32772	; The activation has changed to a different top-level, unowned window.

/**
 * 参考：
 * https://docs.microsoft.com/en-us/windows/win32/controls/wm-vscroll
 */
global WM_VSCROLL := 0x0115
global SB_BOTTOM := 7
global SB_TOP := 6
